spring:
  application:
    name: kafka-streams-service
  profiles:
    active: kafka_streams_service
  cloud:
    config:
      name: kafka-streams-service,config-client
      uri: http://config-server:8000
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://config-server:8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2