spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  cloud:
    config:
      name: elastic-query-web-client,config-client
      uri: http://config-server:8000
      enabled: true
      username: spring_cloud_user
      password: spring_cloud_password
  config:
    import: configserver:http://config-server:8000



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2